### ISSUE TITLE
Traceback (most recent call last):   File "wifigod.py", line 17, in <module>     pip.main(['install', 'hexdump']) AttributeError: 'module' object has no attribute 'main'

### ISSUE THREAD

**Issue by ramiKahmed** [blackholesec/wifigod#2]
I currently downloaded this tool and whenever I open it , an error pops up to me  : 
Traceback (most recent call last):
  File "wifigod.py", line 17, in <module>
    pip.main(['install', 'hexdump'])
AttributeError: 'module' object has no attribute 'main'

P.s I tried to run it using python3 and a new error pops up as well ,,

any thoughts ??!

**Comment by Mikewins1** [comment]
I am having the exact same problem.

**Comment by blackholesec** [comment]
@ramiKahmed @Mikewins1 This issue is occurring in the latest releases of Python 2.7, any time this error arises you can fix it by manually installing the library (pip install libname) in this case hexdump was the library in which was not pre-installed, you can fix it by typing: pip install hexdump

**Comment by Mikewins1** [comment]
I did that and now I get this...

Traceback (most recent call last):
  File "./wifigod.py", line 31, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

**Comment by blackholesec** [comment]
@Mikewins1 If you respond with your current OS and python release I can troubleshoot and rectify the situation.

**Comment by Mikewins1** [comment]
Kali Linux 4.17.0-kali-amd64 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU/Linux

Python 2.7.15

**Comment by f3max** [comment]
@ramiKahmed  same error. kali 2018.3.. i fixed..
pip install hexdump
